[[dependency]]
org = "wso2"
name = "choreo.sendemail"
version = "0.3.0"

[[dependency]]
org = "ballerinax"
name = "worldbank"
version = "0.6.0"

[[dependency]]
org = "ballerinax"
name = "covid19"
version = "0.6.0"


